// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi4387BdlrP3HZ1dEh7J-XOtsKPpLxFYI',
    appId: '1:71175460236:web:7e0831865462c1ff3bb2a9',
    messagingSenderId: '71175460236',
    projectId: 'ecommerceapp-7be48',
    authDomain: 'ecommerceapp-7be48.firebaseapp.com',
    storageBucket: 'ecommerceapp-7be48.appspot.com',
    measurementId: 'G-ZRTQR8XSZR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2peDtIWQit2gt93IF0Saqne7usLbOOe8',
    appId: '1:71175460236:android:5476c1eecbb94eec3bb2a9',
    messagingSenderId: '71175460236',
    projectId: 'ecommerceapp-7be48',
    storageBucket: 'ecommerceapp-7be48.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADls4vGxo_O0tSAoCv8DusD_LwfUfPqBI',
    appId: '1:71175460236:ios:295fe6c6403b366e3bb2a9',
    messagingSenderId: '71175460236',
    projectId: 'ecommerceapp-7be48',
    storageBucket: 'ecommerceapp-7be48.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADls4vGxo_O0tSAoCv8DusD_LwfUfPqBI',
    appId: '1:71175460236:ios:295fe6c6403b366e3bb2a9',
    messagingSenderId: '71175460236',
    projectId: 'ecommerceapp-7be48',
    storageBucket: 'ecommerceapp-7be48.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBi4387BdlrP3HZ1dEh7J-XOtsKPpLxFYI',
    appId: '1:71175460236:web:70ac9431ad5e07113bb2a9',
    messagingSenderId: '71175460236',
    projectId: 'ecommerceapp-7be48',
    authDomain: 'ecommerceapp-7be48.firebaseapp.com',
    storageBucket: 'ecommerceapp-7be48.appspot.com',
    measurementId: 'G-BGJP1NG8ZR',
  );
}
